version: "3.10"
services:
  worker:
    build: .
    environment:
      - APP_ID=${APP_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - CAPTION_TEXT=$CAPTION_TEXT}
      - CAPTION_POSITION=${CAPTION_POSITION}
